services:
  api:
    container_name: api
    build:
      context: ./services/api
    ports:
      - '3000:3000'
    env_file: ./services/api/.env
    environment:
      NODE_ENV: development
    restart: unless-stopped

  cache:
    container_name: cache
    build:
      context: ./services/cache
    ports:
      - "8080:80"
    environment:
      UPSTREAM_URL: http://api:3000
    depends_on:
      - api
    restart: unless-stopped
